version: 1
update_configs:
  - package-manager: "ruby:bundler"
    directory: "/"
    schedule:
      interval: "weekly"
      allowed_updates:
        match:
          update_type: "all"
    version_requirement_updates: "off"
